package com.example.barandgrillownerpanel.data.export

import org.apache.pdfbox.pdmodel.PDDocument
import org.apache.pdfbox.pdmodel.PDPage
import org.apache.pdfbox.pdmodel.PDPageContentStream
import org.apache.pdfbox.pdmodel.common.PDRectangle
import org.apache.pdfbox.pdmodel.font.PDType1Font
import org.apache.pdfbox.pdmodel.font.Standard14Fonts
import java.io.FileOutputStream
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

object PdfReportService {
    private const val PAGE_HEIGHT = 800f
    private const val MARGIN = 50f
    private const val FOOTER_Y = 40f
    private var currentPage = 0
    private var yPosition = 750f

    fun generateReport(
        filePath: String,
        type: PdfReportType,
        period: ExportPeriod,
        businessName: String,
        data: Map<String, Any>
    ) {
        val document = PDDocument()
        currentPage = 0
        yPosition = 750f
        
        addNewPage(document)
        
        val fontBold = PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD)
        val fontNormal = PDType1Font(Standard14Fonts.FontName.HELVETICA)
        
        var contentStream = PDPageContentStream(document, document.getPage(currentPage))

        fun write(text: String, font: PDType1Font, size: Float) {
            if (yPosition < FOOTER_Y) {
                contentStream.endText()
                contentStream.close()
                addNewPage(document)
                contentStream = PDPageContentStream(document, document.getPage(currentPage))
                yPosition = 750f
            }
            contentStream.beginText()
            contentStream.setFont(font, size)
            contentStream.newLineAtOffset(MARGIN, yPosition)
            contentStream.showText(text)
            contentStream.endText()
            yPosition -= (size + 8f)
        }

        // Header
        write("KLIX ENTERPRISE POS", fontBold, 20f)
        write(type.label, fontBold, 16f)
        write("Business: $businessName", fontNormal, 12f)
        write("Period: ${period.label}", fontNormal, 12f)
        write("Generated: ${LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))}", fontNormal, 10f)
        yPosition -= 20f
        write("Financial Summary", fontBold, 14f)
        yPosition -= 10f

        // Data rows
        val metrics = (data["metrics"] as? Map<*, *>)
            ?.mapNotNull { (key, value) ->
                val label = key as? String ?: return@mapNotNull null
                val amount = when (value) {
                    is Number -> value.toDouble()
                    is String -> value.toDoubleOrNull()
                    else -> null
                }
                amount?.let { label to it }
            }
            ?.toMap() ?: emptyMap()

        val items = (data["items"] as? List<*>)
            ?.mapNotNull { item ->
                @Suppress("UNCHECKED_CAST")
                (item as? Map<*, *>)?.mapNotNull { (itemKey, itemValue) ->
                    val key = itemKey as? String ?: return@mapNotNull null
                    key to itemValue
                }?.toMap() as? Map<String, Any>
            } ?: emptyList()
        
        metrics.forEach { (label, value) ->
            write("$label: ${String.format("%.2f", value)} MK", fontNormal, 12f)
        }

        // Detail section
        if (items.isNotEmpty()) {
            yPosition -= 15f
            write("Details", fontBold, 14f)
            yPosition -= 5f
            
            // Column headers
            write("Item                          Amount       Date", fontBold, 11f)
            yPosition -= 3f
            write("─".repeat(60), fontNormal, 10f)
            
            items.forEach { item ->
                val name = (item["name"] as? String ?: "").take(25)
                val amount = when (val a = item["amount"]) {
                    is Double -> String.format("%.2f", a)
                    is Number -> String.format("%.2f", a.toDouble())
                    else -> "0.00"
                }
                val date = item["date"] as? String ?: ""
                write("$name${" ".repeat(25 - name.length)}$amount${" ".repeat(12 - amount.length)}$date", fontNormal, 10f)
            }
        }

        // Footer
        if (yPosition < FOOTER_Y) {
            contentStream.endText()
            contentStream.close()
            addNewPage(document)
            contentStream = PDPageContentStream(document, document.getPage(currentPage))
            yPosition = 750f
        }
        write("Report generated by KLIX POS System", fontNormal, 8f)

        contentStream.endText()
        contentStream.close()
        document.save(FileOutputStream(filePath))
        document.close()
    }

    private fun addNewPage(document: PDDocument) {
        val page = PDPage(PDRectangle.A4)
        document.addPage(page)
        currentPage = document.numberOfPages - 1
        yPosition = 750f
    }
}
